/**
 * Core public API of the cases feature: what the always-loaded app shell and
 * the core of other features may import without pulling in any screen
 * (ARCHITECTURE.md §3, "Two public files"). Query keys, the realtime handlers,
 * the case readers, the shared case labels and the types. No components and
 * nothing that reaches one: src/test/architecture.test.ts checks it.
 */
export { availabilityKeys, caseKeys } from './api'
export { useAvailabilityPresence, useToReplyCount } from './hooks/use-analyst-shell'
export {
  applyCaseSummaryToInboxes,
  readCaseSummary,
  readEscalation,
  registerCasesRealtime,
} from './realtime'
export {
  CASE_CHANNEL,
  CASE_PRIORITY,
  CASE_STATUS,
  CASE_TYPE,
  CASE_TYPE_OPTIONS,
  CLOSE_REASONS,
  ESCALATED_MARKER,
  ESCALATION_STATE,
  ESCALATION_WAIT_LONG_MS,
  ESCALATION_WAIT_RISK_MS,
  INBOX_FILTERS,
  MAX_ESCALATION_TEXT,
  OPEN_CASE_STATUS,
  caseCardFacts,
  caseLifecycleStatus,
  casePriority,
  caseStatus,
  caseType,
  caseTypeMenuLabel,
  channelFact,
  caseChannel,
  channelLabel,
  closeReasonLabel,
  closeReasonOption,
  compareByUrgency,
  countryName,
  escalationWaitFact,
  isAttendedEscalation,
  filterChipLabel,
  formatSla,
  parseInboxStatus,
  inboxStatusMeta,
  isNewerCase,
  isUrgentPriority,
  PRIORITY_OPTIONS,
  RATING_SCALE,
  priorityFact,
  priorityLabel,
  priorityMenuLabel,
  ratingFact,
  ratingLabel,
  ratingOption,
  slaFact,
  sortByUrgency,
  urgencyGroup,
} from './model'
export type {
  CaseChannelConfig,
  CasePriorityConfig,
  CaseStatusConfig,
  CaseStatusKey,
  CaseTypeConfig,
  CloseReasonOption,
  InboxFilter,
  InboxStatusMeta,
  RatingOption,
  RatingScore,
  SlaLevel,
  SlaDisplay,
} from './model'
export type {
  Availability,
  AvailabilityStatus,
  CaseChannel,
  CasePriority,
  CaseRating,
  CaseStatus,
  CaseSummary,
  CaseType,
  CloseReason,
  Escalation,
  EscalationState,
  InboxCounts,
  InboxResponse,
  InboxStatus,
} from './types'
