/**
 * GENERATED by `pnpm gen:api` from backend/openapi.json. Do not edit by hand.
 * Import it only from `src/lib/api/client.ts` (the API boundary).
 */
export interface paths {
  '/api/v1/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Check email and password; always asks for a second factor
     * @description Wrong credentials return `invalid_credentials` with `remainingAttempts`; the fifth consecutive failure returns `account_locked` (423) with `unlockAt`.
     */
    post: operations['auth_login']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** End the current session (also closes its realtime sockets) */
    post: operations['auth_logout']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** The signed-in staff member and session */
    get: operations['auth_me']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/mfa': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Verify the second factor and start a session
     * @description Development code: `000000`. Use the returned token as `Authorization: Bearer`. A wrong code returns `mfa_invalid` with `remainingAttempts`; wrong codes also count toward the account lockout, so the failure that reaches it returns `account_locked` (423) with `unlockAt`, as does any attempt while the account is locked.
     */
    post: operations['auth_verify_mfa']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Liveness and dependency checks */
    get: operations['system_health']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/meta': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** API version and build */
    get: operations['system_meta']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/staff': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List active staff, optionally by role */
    get: operations['people_list_staff']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** HealthResponse */
    HealthResponse: {
      /** Checks */
      checks: {
        [key: string]: 'ok' | 'failing'
      }
      /**
       * Status
       * @enum {string}
       */
      status: 'ok' | 'degraded'
    }
    /**
     * Language
     * @enum {string}
     */
    Language: 'es' | 'pt'
    /** LoginRequest */
    LoginRequest: {
      /**
       * Email
       * @example daniela.rios@latambank.example
       */
      email: string
      /**
       * Password
       * @example demo1234
       */
      password: string
    }
    /** LoginResponse */
    LoginResponse: {
      /** Challengeid */
      challengeId: string
      /**
       * Expiresat
       * Format: date-time
       */
      expiresAt: string
      /** Methods */
      methods: components['schemas']['MfaMethod'][]
      /** Mfarequired */
      mfaRequired: boolean
    }
    /** MeResponse */
    MeResponse: {
      session: components['schemas']['SessionOut']
      staff: components['schemas']['StaffOut']
    }
    /** MetaResponse */
    MetaResponse: {
      /** Apiversion */
      apiVersion: string
      /** Build */
      build: string
      /** Environment */
      environment: string
      /** Name */
      name: string
      /** Version */
      version: string
    }
    /**
     * MfaMethod
     * @enum {string}
     */
    MfaMethod: 'totp' | 'sms' | 'backup_code'
    /** MfaRequest */
    MfaRequest: {
      /** Challengeid */
      challengeId: string
      /**
       * Code
       * @example 000000
       */
      code: string
      /** @default totp */
      method: components['schemas']['MfaMethod']
    }
    /**
     * ProblemCode
     * @enum {string}
     */
    ProblemCode:
      | 'invalid_credentials'
      | 'mfa_invalid'
      | 'mfa_challenge_invalid'
      | 'account_locked'
      | 'unauthenticated'
      | 'session_expired'
      | 'forbidden'
      | 'not_found'
      | 'method_not_allowed'
      | 'conflict'
      | 'concurrent_update'
      | 'invalid_transition'
      | 'invalid_value'
      | 'policy_violation'
      | 'validation_error'
      | 'domain_error'
      | 'application_error'
      | 'invalid_topic'
      | 'invalid_message'
      | 'http_error'
      | 'internal_error'
    /**
     * ProblemDetails
     * @description RFC 7807 problem. ``code`` is the stable machine identifier clients branch on.
     *
     *     The optional members below are the documented extensions; a domain error may add other
     *     structured details (e.g. ``currentStatus``), hence ``additionalProperties``.
     */
    ProblemDetails: {
      code: components['schemas']['ProblemCode']
      /**
       * Detail
       * @default null
       */
      detail: string | null
      /**
       * Errors
       * @description validation_error: one entry per invalid field.
       * @default null
       */
      errors: components['schemas']['ValidationIssue'][] | null
      /**
       * Instance
       * @default null
       */
      instance: string | null
      /**
       * Remainingattempts
       * @description invalid_credentials, mfa_invalid: failed attempts left before the lock.
       * @default null
       */
      remainingAttempts: number | null
      /**
       * Requestid
       * @default null
       */
      requestId: string | null
      /**
       * Requiredroles
       * @description forbidden: roles that may perform the action.
       * @default null
       */
      requiredRoles: components['schemas']['StaffRole'][] | null
      /** Status */
      status: number
      /** Title */
      title: string
      /**
       * Type
       * @example urn:cc-platform:problem:account_locked
       */
      type: string
      /**
       * Unlockat
       * @description account_locked: when the lock ends.
       * @default null
       */
      unlockAt: string | null
    } & {
      [key: string]: unknown
    }
    /** SessionOut */
    SessionOut: {
      /**
       * Expiresat
       * Format: date-time
       */
      expiresAt: string
      /** Id */
      id: string
    }
    /** SessionResponse */
    SessionResponse: {
      session: components['schemas']['SessionOut']
      staff: components['schemas']['StaffOut']
      /** Token */
      token: string
      /**
       * Tokentype
       * @default Bearer
       * @constant
       */
      tokenType: 'Bearer'
    }
    /**
     * StaffLevel
     * @description Analyst seniority; drives abono limits (policies R7/R8).
     * @enum {string}
     */
    StaffLevel: 'Junior' | 'Mid-Senior' | 'Senior' | 'Specialist'
    /** StaffListResponse */
    StaffListResponse: {
      /** Items */
      items: components['schemas']['StaffOut'][]
    }
    /** StaffOut */
    StaffOut: {
      /** Email */
      email: string
      /** Id */
      id: string
      /** Languages */
      languages: components['schemas']['Language'][]
      level: components['schemas']['StaffLevel']
      /** Name */
      name: string
      /** Requiresfoureyes */
      requiresFourEyes: boolean
      /** Roles */
      roles: components['schemas']['StaffRole'][]
      /** Team */
      team: string
    }
    /**
     * StaffRole
     * @description Platform roles. They combine: one person may hold several (brief §1).
     * @enum {string}
     */
    StaffRole: 'analyst' | 'supervisor' | 'automation' | 'admin'
    /** ValidationIssue */
    ValidationIssue: {
      /** Loc */
      loc: string[]
      /** Msg */
      msg: string
      /** Type */
      type: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  auth_login: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LoginResponse']
        }
      }
      /** @description Problem details (RFC 7807) */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
      /** @description Problem details (RFC 7807) */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
      /** @description Problem details (RFC 7807) */
      423: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
    }
  }
  auth_logout: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Problem details (RFC 7807) */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
    }
  }
  auth_me: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MeResponse']
        }
      }
      /** @description Problem details (RFC 7807) */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
    }
  }
  auth_verify_mfa: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['MfaRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SessionResponse']
        }
      }
      /** @description Problem details (RFC 7807) */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
      /** @description Problem details (RFC 7807) */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
      /** @description Problem details (RFC 7807) */
      423: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
    }
  }
  system_health: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthResponse']
        }
      }
      /** @description A dependency is failing */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthResponse']
        }
      }
    }
  }
  system_meta: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MetaResponse']
        }
      }
    }
  }
  people_list_staff: {
    parameters: {
      query?: {
        /** @description Only staff holding this role */
        role?: components['schemas']['StaffRole'] | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['StaffListResponse']
        }
      }
      /** @description Problem details (RFC 7807) */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
      /** @description Problem details (RFC 7807) */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
      /** @description Problem details (RFC 7807): validation_error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
    }
  }
}
