/**
 * GENERATED by `pnpm gen:api` from backend/openapi.json. Do not edit by hand.
 * Import it only from `src/lib/api/client.ts` (the API boundary).
 */
export interface paths {
  '/api/v1/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Check email and password; always asks for a second factor
     * @description Wrong credentials return `invalid_credentials` with `remainingAttempts`; the fifth consecutive failure returns `account_locked` (423) with `unlockAt`.
     */
    post: operations['auth_login']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** End the current session (also closes its realtime sockets) */
    post: operations['auth_logout']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** The signed-in staff member and session */
    get: operations['auth_me']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/mfa': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Verify the second factor and start a session
     * @description Development code: `000000`. Use the returned token as `Authorization: Bearer`. A wrong code returns `mfa_invalid` with `remainingAttempts`; wrong codes also count toward the account lockout, so the failure that reaches it returns `account_locked` (423) with `unlockAt`, as does any attempt while the account is locked.
     */
    post: operations['auth_verify_mfa']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/cases/inbox': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * The caller's cases ("Casos") and the status counters
     * @description No `status` = Todos (the open cases); `status=closed` = the caller's cases closed in the last 7 days. `counts` always cover the whole inbox (the counters are the filters), whatever `status` and `q` select. Open lists: `new` and `to_reply` first, then `waiting`, each by the oldest last interaction; `closed`: the most recently closed first. At most 200 items.
     */
    get: operations['cases_get_inbox']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/cases/{caseId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Case detail: customer, "Cómo llegó a ti", closure, capabilities */
    get: operations['cases_get_case']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/cases/{caseId}/close': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Close the case with a reason; the customer is told the conversation ended
     * @description Assignee only, from `assigned` or `in_progress`. The note is internal (trimmed, blank becomes null, at most 500 characters); the customer never sees the reason or the note. Their next message opens a new case linked to this one.
     */
    post: operations['cases_close_case']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/cases/{caseId}/history': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * "Casos anteriores de este cliente": the customer's other cases
     * @description Any status, excluding `caseId`, newest `openedAt` first, at most 20 (`total` is the full count). Whoever may read `caseId` may read every listed case (read-only).
     */
    get: operations['cases_get_case_history']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/cases/{caseId}/read': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Move the assignee's read cursor (opening a new case starts it) */
    post: operations['cases_mark_read']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/cases/{caseId}/turns': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * A page of the transcript (ascending sequence)
     * @description No params → the latest page. `cursor` (from `olderCursor`) → the page before it. `afterSequence` → turns after it (gap fill after a reconnect). `cursor` and `afterSequence` are mutually exclusive.
     */
    get: operations['cases_list_turns']
    put?: never
    /**
     * Reply to the customer (assignee only)
     * @description Idempotent on `clientMessageId` (= `Idempotency-Key`): a retry with the same text answers 200 with `Idempotent-Replayed: true` and the original turn; the same id with another text is `idempotency_conflict`. Moves a `new` case to `in_progress`; the first reply stops the first-response SLA.
     */
    post: operations['cases_post_turn']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/customer/conversation': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** My current conversation (open case, else the last closed one) and its turns */
    get: operations['customer_get_conversation']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/customer/conversation/turns': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Write to the bank: opens a case when none is open, else appends to it
     * @description Idempotent on `clientMessageId` (= `Idempotency-Key`): a retry with the same text answers 200 with `Idempotent-Replayed: true`. With no open case (never wrote, or the last one closed) a new case opens, linked to the previous closed one, and is assigned in the same request (`with_agent`) or waits in the queue (`waiting_agent`).
     */
    post: operations['customer_post_turn']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/customer/conversations': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * My past conversations (closed, other than the current one)
     * @description Newest `openedAt` first, at most 20.
     */
    get: operations['customer_list_past_conversations']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/customer/conversations/{caseId}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * One of my conversations with its turns (read-only)
     * @description Up to the latest 200 turns meant for the customer, ascending.
     */
    get: operations['customer_get_past_conversation']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/customer/demo-customers': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Seeded customers for the simulator picker (no auth; empty without demo data)
     * @description Simulator customers first, then every other seeded customer by name.
     */
    get: operations['customer_list_demo_customers']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/customer/sessions': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Start a customer session (channel identity = app/web session) */
    post: operations['customer_create_session']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Liveness and dependency checks */
    get: operations['system_health']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/me/availability': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** My availability (never set = paused) */
    get: operations['availability_get_availability']
    /** Set my availability (same status = no change, no event) */
    put: operations['availability_set_availability']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/meta': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** API version and build */
    get: operations['system_meta']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/staff': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** List active staff, optionally by role */
    get: operations['people_list_staff']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** AssignmentOut */
    AssignmentOut: {
      /** Analystid */
      analystId: string
      /** Analystname */
      analystName: string
      /**
       * Assignedat
       * Format: date-time
       */
      assignedAt: string
      /** Id */
      id: string
      /** Policyruleid */
      policyRuleId: string | null
      /**
       * Queuelabel
       * @description Set when the case waited in a queue.
       */
      queueLabel: string | null
      reason: components['schemas']['AssignmentReason']
      /**
       * Waitedseconds
       * @description Queue wait (queue_drained), else null.
       */
      waitedSeconds: number | null
    }
    /**
     * AssignmentReason
     * @description Why a case reached its analyst. Slice 3 adds ``manual`` (a supervisor).
     * @enum {string}
     */
    AssignmentReason: 'language_least_loaded' | 'queue_drained'
    /** Availability */
    Availability: {
      /**
       * Since
       * Format: date-time
       */
      since: string
      status: components['schemas']['AvailabilityStatus']
    }
    /**
     * AvailabilityStatus
     * @enum {string}
     */
    AvailabilityStatus: 'available' | 'paused'
    /** CaseCapabilities */
    CaseCapabilities: {
      /** Canclose */
      canClose: boolean
      /** Canreply */
      canReply: boolean
      replyBlockedReason: components['schemas']['ReplyBlockedReason'] | null
    }
    /**
     * CaseChannel
     * @description Where the customer writes from (the simulator stands in for both).
     * @enum {string}
     */
    CaseChannel: 'app_chat' | 'web_chat'
    /** CaseClosure */
    CaseClosure: {
      /**
       * Closedat
       * Format: date-time
       */
      closedAt: string
      /** Closedbyid */
      closedById: string
      /** Closedbyname */
      closedByName: string | null
      /**
       * Note
       * @description Internal note: staff only, never sent to the customer.
       */
      note: string | null
      reason: components['schemas']['CloseReason']
    }
    /** CaseCustomer */
    CaseCustomer: {
      /** City */
      city: string
      country: components['schemas']['CountryCode']
      /** Displayname */
      displayName: string
      /** Id */
      id: string
      language: components['schemas']['Language']
      locale: components['schemas']['CustomerLocale']
    }
    /** CaseDetail */
    CaseDetail: {
      /** @description "Cómo llegó a ti". */
      assignment: components['schemas']['AssignmentOut'] | null
      /** @description Computed for the caller. */
      capabilities: components['schemas']['CaseCapabilities']
      case: components['schemas']['CaseSummary']
      closure: components['schemas']['CaseClosure'] | null
      customer: components['schemas']['CaseCustomer']
      /**
       * Previouscasecount
       * @description Other cases of this customer (any status).
       */
      previousCaseCount: number
    }
    /** CaseHistory */
    CaseHistory: {
      /**
       * Items
       * @description Newest openedAt first, at most 20.
       */
      items: components['schemas']['CaseHistoryItem'][]
      /**
       * Total
       * @description All other cases of the customer.
       */
      total: number
    }
    /** CaseHistoryItem */
    CaseHistoryItem: {
      /**
       * Analystid
       * @description Who held it (the assignee).
       */
      analystId: string | null
      /** Analystname */
      analystName: string | null
      channel: components['schemas']['CaseChannel']
      closeReason: components['schemas']['CloseReason'] | null
      /** Closedat */
      closedAt: string | null
      /** Id */
      id: string
      /**
       * Openedat
       * Format: date-time
       */
      openedAt: string
      /**
       * Preview
       * @description Last message text (at most 140 characters).
       */
      preview: string | null
      status: components['schemas']['CaseStatus']
    }
    /**
     * CasePriority
     * @description Drives the first-response SLA target. Live cases open as ``medium``.
     * @enum {string}
     */
    CasePriority: 'low' | 'medium' | 'high'
    /**
     * CaseStatus
     * @description Stored state machine of a case (see ``Case``).
     * @enum {string}
     */
    CaseStatus: 'queued' | 'assigned' | 'in_progress' | 'closed'
    /** CaseSummary */
    CaseSummary: {
      /** Assignedanalystid */
      assignedAnalystId: string | null
      channel: components['schemas']['CaseChannel']
      closeReason: components['schemas']['CloseReason'] | null
      /** Closedat */
      closedAt: string | null
      customer: components['schemas']['CustomerRef']
      /**
       * Firstresponseat
       * @description The first analyst message (the SLA stops); null while pending.
       */
      firstResponseAt: string | null
      /** Id */
      id: string
      /** @description null while the case is queued. */
      inboxStatus: components['schemas']['InboxStatus'] | null
      language: components['schemas']['Language']
      /**
       * Lastinteractionat
       * Format: date-time
       */
      lastInteractionAt: string
      /** Lastsequence */
      lastSequence: number
      /**
       * Openedat
       * Format: date-time
       */
      openedAt: string
      /** Preview */
      preview: string | null
      previewAuthorRole: components['schemas']['TurnAuthorRole'] | null
      /**
       * Previouscaseid
       * @description The closed case this one continues ("Volvió a escribir").
       */
      previousCaseId: string | null
      priority: components['schemas']['CasePriority']
      /**
       * Sladueat
       * Format: date-time
       * @description First-response due time.
       */
      slaDueAt: string
      status: components['schemas']['CaseStatus']
      /** Unreadcount */
      unreadCount: number
      /**
       * Version
       * @description Realtime: apply only when newer than the cached one.
       */
      version: number
    }
    /** CloseCaseRequest */
    CloseCaseRequest: {
      /** Note */
      note: string | null
      reason: components['schemas']['CloseReason']
    }
    /**
     * CloseReason
     * @description Why the assignee closed a case. Team-generated list (not from the dataset).
     * @enum {string}
     */
    CloseReason: 'resolved' | 'customer_unresponsive' | 'duplicate' | 'out_of_scope' | 'other'
    /**
     * CountryCode
     * @enum {string}
     */
    CountryCode: 'CO' | 'MX' | 'AR' | 'BR'
    /** CreateCustomerSessionRequest */
    CreateCustomerSessionRequest: {
      /**
       * Channel
       * @description Default app_chat; ignored while the customer has an open case.
       */
      channel?: ('app_chat' | 'web_chat') | null
      /** Customerid */
      customerId: string
    }
    /** CustomerConversation */
    CustomerConversation: {
      /**
       * Agentname
       * @description Assignee first name while with_agent; on a closed case, who attended it.
       */
      agentName: string | null
      /** Caseid */
      caseId: string
      channel: components['schemas']['CaseChannel']
      /** Closedat */
      closedAt: string | null
      language: components['schemas']['Language']
      /**
       * Lastsequence
       * @description Highest sequence among customer-visible turns.
       */
      lastSequence: number
      /**
       * Openedat
       * Format: date-time
       */
      openedAt: string
      /**
       * Previouscaseid
       * @description The closed case this one continues.
       */
      previousCaseId: string | null
      status: components['schemas']['CustomerConversationStatus']
    }
    /** CustomerConversationDetail */
    CustomerConversationDetail: {
      conversation: components['schemas']['CustomerConversation']
      /**
       * Turns
       * @description Up to the latest 200, ascending.
       */
      turns: components['schemas']['CustomerTurn'][]
    }
    /** CustomerConversationList */
    CustomerConversationList: {
      /**
       * Items
       * @description Closed conversations other than the current one, newest first (≤ 20).
       */
      items: components['schemas']['CustomerConversationSummary'][]
    }
    /** CustomerConversationResponse */
    CustomerConversationResponse: {
      conversation: components['schemas']['CustomerConversation'] | null
      /**
       * Pastconversationcount
       * @description Closed conversations other than the current one.
       */
      pastConversationCount: number
      /** Turns */
      turns: components['schemas']['CustomerTurn'][]
    }
    /**
     * CustomerConversationStatus
     * @description Customer-facing projection of ``CaseStatus``.
     * @enum {string}
     */
    CustomerConversationStatus: 'waiting_agent' | 'with_agent' | 'closed'
    /** CustomerConversationSummary */
    CustomerConversationSummary: {
      /**
       * Agentname
       * @description First name of who attended it.
       */
      agentName: string | null
      /** Caseid */
      caseId: string
      channel: components['schemas']['CaseChannel']
      /** Closedat */
      closedAt: string | null
      /**
       * Openedat
       * Format: date-time
       */
      openedAt: string
      /**
       * Preview
       * @description Last message text (at most 140 characters).
       */
      preview: string | null
      status: components['schemas']['CustomerConversationStatus']
    }
    /**
     * CustomerLocale
     * @enum {string}
     */
    CustomerLocale: 'es-CO' | 'es-MX' | 'es-AR' | 'pt-BR'
    /** CustomerRef */
    CustomerRef: {
      /** Displayname */
      displayName: string
      /** Id */
      id: string
    }
    /** CustomerSelf */
    CustomerSelf: {
      /** Displayname */
      displayName: string
      /** Id */
      id: string
      language: components['schemas']['Language']
      locale: components['schemas']['CustomerLocale']
    }
    /** CustomerSessionResponse */
    CustomerSessionResponse: {
      channel: components['schemas']['CaseChannel']
      customer: components['schemas']['CustomerSelf']
      /**
       * Expiresat
       * Format: date-time
       */
      expiresAt: string
      /** Token */
      token: string
    }
    /** CustomerTurn */
    CustomerTurn: {
      /** Authorname */
      authorName: string | null
      authorRole: components['schemas']['CustomerTurnAuthor']
      /**
       * Clientmessageid
       * @description Only on the customer's own messages.
       */
      clientMessageId: string | null
      /**
       * Createdat
       * Format: date-time
       */
      createdAt: string
      /** Id */
      id: string
      /**
       * Kind
       * @enum {string}
       */
      kind: 'message' | 'notice'
      language: components['schemas']['Language']
      /**
       * Sequence
       * @description Case sequence (customer-visible turns may skip numbers).
       */
      sequence: number
      /** Text */
      text: string
    }
    /**
     * CustomerTurnAuthor
     * @description Customer-facing author of a turn.
     * @enum {string}
     */
    CustomerTurnAuthor: 'customer' | 'analyst' | 'system'
    /** DemoConversation */
    DemoConversation: {
      /** Caseid */
      caseId: string
      channel: components['schemas']['CaseChannel']
      status: components['schemas']['CustomerConversationStatus']
    }
    /** DemoCustomer */
    DemoCustomer: {
      /** City */
      city: string
      /** Closedconversationcount */
      closedConversationCount: number
      country: components['schemas']['CountryCode']
      /** Displayname */
      displayName: string
      /** Id */
      id: string
      language: components['schemas']['Language']
      locale: components['schemas']['CustomerLocale']
      /** @description Only an open case. */
      openConversation: components['schemas']['DemoConversation'] | null
      /**
       * Suggestions
       * @description Opener chips in the customer's own voice.
       */
      suggestions: string[]
    }
    /** DemoCustomerList */
    DemoCustomerList: {
      /**
       * Items
       * @description Simulator customers first, then every other seeded customer by name.
       */
      items: components['schemas']['DemoCustomer'][]
    }
    /** HealthResponse */
    HealthResponse: {
      /** Checks */
      checks: {
        [key: string]: 'ok' | 'failing'
      }
      /**
       * Status
       * @enum {string}
       */
      status: 'ok' | 'degraded'
    }
    /** InboxCounts */
    InboxCounts: {
      /**
       * All
       * @description Open cases: new + toReply + waiting.
       */
      all: number
      /**
       * Closed
       * @description Cases closed in the last 7 days.
       */
      closed: number
      /**
       * Computedat
       * Format: date-time
       */
      computedAt: string
      /** New */
      new: number
      /** Toreply */
      toReply: number
      /** Waiting */
      waiting: number
    }
    /** InboxResponse */
    InboxResponse: {
      /** @description Always the whole inbox (ignores status and q). */
      counts: components['schemas']['InboxCounts']
      /** Items */
      items: components['schemas']['CaseSummary'][]
      /**
       * Servertime
       * Format: date-time
       */
      serverTime: string
    }
    /**
     * InboxStatus
     * @description Bucket of a case in "Casos" (derived from ``CaseStatus``, never stored).
     * @enum {string}
     */
    InboxStatus: 'new' | 'to_reply' | 'waiting' | 'closed'
    /**
     * Language
     * @enum {string}
     */
    Language: 'es' | 'pt'
    /** LoginRequest */
    LoginRequest: {
      /**
       * Email
       * @example daniela.rios@latambank.example
       */
      email: string
      /**
       * Password
       * @example demo1234
       */
      password: string
    }
    /** LoginResponse */
    LoginResponse: {
      /** Challengeid */
      challengeId: string
      /**
       * Expiresat
       * Format: date-time
       */
      expiresAt: string
      /** Methods */
      methods: components['schemas']['MfaMethod'][]
      /** Mfarequired */
      mfaRequired: boolean
    }
    /** MarkReadRequest */
    MarkReadRequest: {
      /** Uptosequence */
      upToSequence: number
    }
    /** MeResponse */
    MeResponse: {
      session: components['schemas']['SessionOut']
      staff: components['schemas']['StaffOut']
    }
    /** MetaResponse */
    MetaResponse: {
      /** Apiversion */
      apiVersion: string
      /** Build */
      build: string
      /** Environment */
      environment: string
      /** Name */
      name: string
      /** Version */
      version: string
    }
    /**
     * MfaMethod
     * @enum {string}
     */
    MfaMethod: 'totp' | 'sms' | 'backup_code'
    /** MfaRequest */
    MfaRequest: {
      /** Challengeid */
      challengeId: string
      /**
       * Code
       * @example 000000
       */
      code: string
      /** @default totp */
      method: components['schemas']['MfaMethod']
    }
    /** PostAnalystTurnRequest */
    PostAnalystTurnRequest: {
      /**
       * Clientmessageid
       * @description Client-generated id (UUID v4); also the Idempotency-Key header.
       * @example 0b8f6a52-6f0e-4c1e-9d55-2f5a0c7d9e10
       */
      clientMessageId: string
      /** Text */
      text: string
    }
    /** PostCustomerTurnRequest */
    PostCustomerTurnRequest: {
      /**
       * Clientmessageid
       * @description Client-generated id (UUID v4); also the Idempotency-Key header.
       * @example 0b8f6a52-6f0e-4c1e-9d55-2f5a0c7d9e10
       */
      clientMessageId: string
      /** Text */
      text: string
    }
    /** PostCustomerTurnResponse */
    PostCustomerTurnResponse: {
      /** Casecreated */
      caseCreated: boolean
      conversation: components['schemas']['CustomerConversation']
      turn: components['schemas']['CustomerTurn']
    }
    /** PostTurnResponse */
    PostTurnResponse: {
      case: components['schemas']['CaseSummary']
      turn: components['schemas']['Turn']
    }
    /**
     * ProblemCode
     * @enum {string}
     */
    ProblemCode:
      | 'invalid_credentials'
      | 'mfa_invalid'
      | 'mfa_challenge_invalid'
      | 'account_locked'
      | 'unauthenticated'
      | 'session_expired'
      | 'forbidden'
      | 'not_found'
      | 'method_not_allowed'
      | 'conflict'
      | 'concurrent_update'
      | 'invalid_transition'
      | 'case_not_assigned'
      | 'case_closed'
      | 'idempotency_conflict'
      | 'invalid_value'
      | 'policy_violation'
      | 'validation_error'
      | 'domain_error'
      | 'application_error'
      | 'invalid_topic'
      | 'invalid_message'
      | 'http_error'
      | 'internal_error'
    /**
     * ProblemDetails
     * @description RFC 7807 problem. ``code`` is the stable machine identifier clients branch on.
     *
     *     The optional members below are the documented extensions; a domain error may add other
     *     structured details (e.g. ``openCaseId`` on ``conflict``), hence
     *     ``additionalProperties``.
     */
    ProblemDetails: {
      code: components['schemas']['ProblemCode']
      /**
       * @description invalid_transition, case_closed: the case status now.
       * @default null
       */
      currentStatus: components['schemas']['CaseStatus'] | null
      /**
       * Detail
       * @default null
       */
      detail: string | null
      /**
       * Errors
       * @description validation_error: one entry per invalid field.
       * @default null
       */
      errors: components['schemas']['ValidationIssue'][] | null
      /**
       * Instance
       * @default null
       */
      instance: string | null
      /**
       * Remainingattempts
       * @description invalid_credentials, mfa_invalid: failed attempts left before the lock.
       * @default null
       */
      remainingAttempts: number | null
      /**
       * Requestid
       * @default null
       */
      requestId: string | null
      /**
       * Requiredroles
       * @description forbidden: roles that may perform the action.
       * @default null
       */
      requiredRoles: components['schemas']['StaffRole'][] | null
      /** Status */
      status: number
      /** Title */
      title: string
      /**
       * Type
       * @example urn:cc-platform:problem:account_locked
       */
      type: string
      /**
       * Unlockat
       * @description account_locked: when the lock ends.
       * @default null
       */
      unlockAt: string | null
    } & {
      [key: string]: unknown
    }
    /**
     * ReplyBlockedReason
     * @enum {string}
     */
    ReplyBlockedReason: 'not_assignee' | 'closed'
    /** SessionOut */
    SessionOut: {
      /**
       * Expiresat
       * Format: date-time
       */
      expiresAt: string
      /** Id */
      id: string
    }
    /** SessionResponse */
    SessionResponse: {
      session: components['schemas']['SessionOut']
      staff: components['schemas']['StaffOut']
      /** Token */
      token: string
      /**
       * Tokentype
       * @default Bearer
       * @constant
       */
      tokenType: 'Bearer'
    }
    /** StaffListResponse */
    StaffListResponse: {
      /** Items */
      items: components['schemas']['StaffOut'][]
    }
    /** StaffOut */
    StaffOut: {
      /** Email */
      email: string
      /** Id */
      id: string
      /** Languages */
      languages: components['schemas']['Language'][]
      /** Name */
      name: string
      /** Roles */
      roles: components['schemas']['StaffRole'][]
      /** Team */
      team: string
    }
    /**
     * StaffRole
     * @description Platform roles. They combine: one person may hold several (brief §1).
     * @enum {string}
     */
    StaffRole: 'analyst' | 'supervisor' | 'admin'
    /** Turn */
    Turn: {
      audience: components['schemas']['TurnAudience']
      /** Authorid */
      authorId: string | null
      /** Authorname */
      authorName: string | null
      authorRole: components['schemas']['TurnAuthorRole']
      /** Caseid */
      caseId: string
      /** Clientmessageid */
      clientMessageId: string | null
      /**
       * Createdat
       * Format: date-time
       */
      createdAt: string
      /** Id */
      id: string
      kind: components['schemas']['TurnKind']
      language: components['schemas']['Language']
      /**
       * Sequence
       * @description 1-based, gap-free per case (staff-only turns included).
       */
      sequence: number
      /** Text */
      text: string
    }
    /**
     * TurnAudience
     * @description ``staff`` turns never reach the customer (REST or socket).
     * @enum {string}
     */
    TurnAudience: 'everyone' | 'staff'
    /**
     * TurnAuthorRole
     * @description Who wrote a turn: the customer, an analyst or the platform (notices, banners).
     * @enum {string}
     */
    TurnAuthorRole: 'customer' | 'analyst' | 'system'
    /**
     * TurnKind
     * @description ``message`` = conversation; ``routing`` = staff-only assignment banner (how the case
     *     arrived); ``notice`` = platform note.
     * @enum {string}
     */
    TurnKind: 'message' | 'routing' | 'notice'
    /** TurnPage */
    TurnPage: {
      /**
       * Items
       * @description Ascending sequence.
       */
      items: components['schemas']['Turn'][]
      /** Lastsequence */
      lastSequence: number
      /** Oldercursor */
      olderCursor: string | null
    }
    /** UpdateAvailabilityRequest */
    UpdateAvailabilityRequest: {
      status: components['schemas']['AvailabilityStatus']
    }
    /** ValidationIssue */
    ValidationIssue: {
      /** Loc */
      loc: string[]
      /** Msg */
      msg: string
      /** Type */
      type: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  auth_login: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LoginResponse']
        }
      }
      /** @description Problem details (RFC 7807) */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
      /** @description Problem details (RFC 7807) */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
      /** @description Problem details (RFC 7807) */
      423: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
    }
  }
  auth_logout: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown
        }
        content?: never
      }
      /** @description Problem details (RFC 7807) */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
    }
  }
  auth_me: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MeResponse']
        }
      }
      /** @description Problem details (RFC 7807) */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
    }
  }
  auth_verify_mfa: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['MfaRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SessionResponse']
        }
      }
      /** @description Problem details (RFC 7807) */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
      /** @description Problem details (RFC 7807) */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
      /** @description Problem details (RFC 7807) */
      423: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
    }
  }
  cases_get_inbox: {
    parameters: {
      query?: {
        /** @description Omit for Todos (open cases) */
        status?: components['schemas']['InboxStatus'] | null
        /** @description Customer name or case id (contains) */
        q?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['InboxResponse']
        }
      }
      /** @description Problem details (RFC 7807) */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
      /** @description Problem details (RFC 7807) */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
      /** @description Problem details (RFC 7807) */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
    }
  }
  cases_get_case: {
    parameters: {
      query?: never
      header?: never
      path: {
        caseId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CaseDetail']
        }
      }
      /** @description Problem details (RFC 7807) */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
      /** @description Problem details (RFC 7807) */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
      /** @description Problem details (RFC 7807) */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
      /** @description Problem details (RFC 7807): validation_error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
    }
  }
  cases_close_case: {
    parameters: {
      query?: never
      header?: never
      path: {
        caseId: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CloseCaseRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CaseDetail']
        }
      }
      /** @description Problem details (RFC 7807) */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
      /** @description Problem details (RFC 7807) */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
      /** @description Problem details (RFC 7807) */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
      /** @description Problem details (RFC 7807) */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
      /** @description Problem details (RFC 7807) */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
    }
  }
  cases_get_case_history: {
    parameters: {
      query?: never
      header?: never
      path: {
        caseId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CaseHistory']
        }
      }
      /** @description Problem details (RFC 7807) */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
      /** @description Problem details (RFC 7807) */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
      /** @description Problem details (RFC 7807) */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
      /** @description Problem details (RFC 7807): validation_error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
    }
  }
  cases_mark_read: {
    parameters: {
      query?: never
      header?: never
      path: {
        caseId: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['MarkReadRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CaseSummary']
        }
      }
      /** @description Problem details (RFC 7807) */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
      /** @description Problem details (RFC 7807) */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
      /** @description Problem details (RFC 7807) */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
      /** @description Problem details (RFC 7807) */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
    }
  }
  cases_list_turns: {
    parameters: {
      query?: {
        cursor?: string | null
        afterSequence?: number | null
        limit?: number
      }
      header?: never
      path: {
        caseId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TurnPage']
        }
      }
      /** @description Problem details (RFC 7807) */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
      /** @description Problem details (RFC 7807) */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
      /** @description Problem details (RFC 7807) */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
      /** @description Problem details (RFC 7807) */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
    }
  }
  cases_post_turn: {
    parameters: {
      query?: never
      header: {
        /** @description Must equal the body `clientMessageId`; a retry with it is a replay. */
        'Idempotency-Key': string
      }
      path: {
        caseId: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PostAnalystTurnRequest']
      }
    }
    responses: {
      /** @description Replay of an already-created turn */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PostTurnResponse']
        }
      }
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PostTurnResponse']
        }
      }
      /** @description Problem details (RFC 7807) */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
      /** @description Problem details (RFC 7807) */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
      /** @description Problem details (RFC 7807) */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
      /** @description Problem details (RFC 7807) */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
      /** @description Problem details (RFC 7807) */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
    }
  }
  customer_get_conversation: {
    parameters: {
      query?: {
        afterSequence?: number | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CustomerConversationResponse']
        }
      }
      /** @description Problem details (RFC 7807) */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
      /** @description Problem details (RFC 7807) */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
    }
  }
  customer_post_turn: {
    parameters: {
      query?: never
      header: {
        /** @description Must equal the body `clientMessageId`; a retry with it is a replay. */
        'Idempotency-Key': string
      }
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PostCustomerTurnRequest']
      }
    }
    responses: {
      /** @description Replay of an already-sent message */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PostCustomerTurnResponse']
        }
      }
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PostCustomerTurnResponse']
        }
      }
      /** @description Problem details (RFC 7807) */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
      /** @description Problem details (RFC 7807) */
      409: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
      /** @description Problem details (RFC 7807) */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
    }
  }
  customer_list_past_conversations: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CustomerConversationList']
        }
      }
      /** @description Problem details (RFC 7807) */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
    }
  }
  customer_get_past_conversation: {
    parameters: {
      query?: never
      header?: never
      path: {
        caseId: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CustomerConversationDetail']
        }
      }
      /** @description Problem details (RFC 7807) */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
      /** @description Problem details (RFC 7807) */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
      /** @description Problem details (RFC 7807): validation_error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
    }
  }
  customer_list_demo_customers: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['DemoCustomerList']
        }
      }
    }
  }
  customer_create_session: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateCustomerSessionRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['CustomerSessionResponse']
        }
      }
      /** @description Problem details (RFC 7807) */
      404: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
      /** @description Problem details (RFC 7807) */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
    }
  }
  system_health: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthResponse']
        }
      }
      /** @description A dependency is failing */
      503: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthResponse']
        }
      }
    }
  }
  availability_get_availability: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Availability']
        }
      }
      /** @description Problem details (RFC 7807) */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
      /** @description Problem details (RFC 7807) */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
    }
  }
  availability_set_availability: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateAvailabilityRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Availability']
        }
      }
      /** @description Problem details (RFC 7807) */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
      /** @description Problem details (RFC 7807) */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
      /** @description Problem details (RFC 7807) */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
    }
  }
  system_meta: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MetaResponse']
        }
      }
    }
  }
  people_list_staff: {
    parameters: {
      query?: {
        /** @description Only staff holding this role */
        role?: components['schemas']['StaffRole'] | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['StaffListResponse']
        }
      }
      /** @description Problem details (RFC 7807) */
      401: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
      /** @description Problem details (RFC 7807) */
      403: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
      /** @description Problem details (RFC 7807): validation_error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/problem+json': components['schemas']['ProblemDetails']
        }
      }
    }
  }
}
