"""Cases context: the case, its transcript, its assignment and the one-open-case rule."""

from cc_platform.domain.cases.assignment import Assignment
from cc_platform.domain.cases.case import Case, CaseClosure, preview_of, search_key
from cc_platform.domain.cases.customer_case_slot import CustomerCaseSlot
from cc_platform.domain.cases.errors import (
    CaseClosedError,
    ChannelNotSupportedError,
    IdempotencyConflictError,
)
from cc_platform.domain.cases.events import (
    CASE_EVENTS,
    CaseAssigned,
    CaseClosed,
    CaseOpened,
    CaseQueued,
    CaseRead,
    CaseStatusChanged,
    TurnCreated,
)
from cc_platform.domain.cases.turn import MAX_TURN_TEXT, Turn, normalize_turn_text
from cc_platform.domain.cases.values import (
    CLOSABLE_STATUSES,
    OPEN_ASSIGNED_STATUSES,
    REPLYABLE_STATUSES,
    AssignmentReason,
    CaseChannel,
    CaseOrigin,
    CasePriority,
    CaseStatus,
    CaseTopic,
    ChannelSessionKind,
    ContactReason,
    CustomerConversationStatus,
    CustomerTurnAuthor,
    FollowUp,
    InboxStatus,
    ResolutionCode,
    TurnAudience,
    TurnAuthorRole,
    TurnKind,
)

__all__ = [
    "CASE_EVENTS",
    "CLOSABLE_STATUSES",
    "MAX_TURN_TEXT",
    "OPEN_ASSIGNED_STATUSES",
    "REPLYABLE_STATUSES",
    "Assignment",
    "AssignmentReason",
    "Case",
    "CaseAssigned",
    "CaseChannel",
    "CaseClosed",
    "CaseClosedError",
    "CaseClosure",
    "CaseOpened",
    "CaseOrigin",
    "CasePriority",
    "CaseQueued",
    "CaseRead",
    "CaseStatus",
    "CaseStatusChanged",
    "CaseTopic",
    "ChannelNotSupportedError",
    "ChannelSessionKind",
    "ContactReason",
    "CustomerCaseSlot",
    "CustomerConversationStatus",
    "CustomerTurnAuthor",
    "FollowUp",
    "IdempotencyConflictError",
    "InboxStatus",
    "ResolutionCode",
    "Turn",
    "TurnAudience",
    "TurnAuthorRole",
    "TurnCreated",
    "TurnKind",
    "normalize_turn_text",
    "preview_of",
    "search_key",
]
