"""Cases context: the case, its transcript, its assignment and the one-open-case rule."""

from cc_platform.domain.cases.assignment import Assignment, ensure_speaks_case_language
from cc_platform.domain.cases.case import (
    MAX_CLOSE_NOTE,
    Case,
    CaseClosure,
    normalize_close_note,
    preview_of,
    search_key,
)
from cc_platform.domain.cases.customer_case_slot import CustomerCaseSlot
from cc_platform.domain.cases.errors import (
    AlreadyRatedError,
    CaseClosedError,
    CaseNotClosedError,
    EscalationNotOpenError,
    EscalationOpenError,
    IdempotencyConflictError,
    LanguageMismatchError,
)
from cc_platform.domain.cases.escalation import (
    ATTENDED_STATES,
    MAX_ESCALATION_TEXT,
    Escalation,
    EscalationState,
    normalize_escalation_text,
)
from cc_platform.domain.cases.events import (
    CASE_EVENTS,
    CaseAssigned,
    CaseClosed,
    CaseFirstResponded,
    CaseOpened,
    CasePriorityChanged,
    CaseQueued,
    CaseRated,
    CaseRead,
    CaseStatusChanged,
    CaseViewed,
    EscalationAcknowledged,
    EscalationAnswered,
    EscalationClosed,
    EscalationOpened,
    EscalationReassigned,
    EscalationTaken,
    EscalationWithdrawn,
    TurnCreated,
)
from cc_platform.domain.cases.rating import (
    MAX_RATING_COMMENT,
    CaseRating,
    normalize_rating_comment,
    normalize_rating_score,
)
from cc_platform.domain.cases.turn import MAX_TURN_TEXT, Turn, normalize_turn_text
from cc_platform.domain.cases.values import (
    CLOSABLE_STATUSES,
    LANGUAGE_RULE_ID,
    OPEN_ASSIGNED_STATUSES,
    REPLYABLE_STATUSES,
    AssignmentReason,
    CaseChannel,
    CasePriority,
    CaseStatus,
    CloseReason,
    CustomerConversationStatus,
    CustomerTurnAuthor,
    InboxStatus,
    TurnAudience,
    TurnAuthorRole,
    TurnKind,
)

__all__ = [
    "ATTENDED_STATES",
    "CASE_EVENTS",
    "CLOSABLE_STATUSES",
    "LANGUAGE_RULE_ID",
    "MAX_CLOSE_NOTE",
    "MAX_ESCALATION_TEXT",
    "MAX_RATING_COMMENT",
    "MAX_TURN_TEXT",
    "OPEN_ASSIGNED_STATUSES",
    "REPLYABLE_STATUSES",
    "AlreadyRatedError",
    "Assignment",
    "AssignmentReason",
    "Case",
    "CaseAssigned",
    "CaseChannel",
    "CaseClosed",
    "CaseClosedError",
    "CaseClosure",
    "CaseFirstResponded",
    "CaseNotClosedError",
    "CaseOpened",
    "CasePriority",
    "CasePriorityChanged",
    "CaseQueued",
    "CaseRated",
    "CaseRating",
    "CaseRead",
    "CaseStatus",
    "CaseStatusChanged",
    "CaseViewed",
    "CloseReason",
    "CustomerCaseSlot",
    "CustomerConversationStatus",
    "CustomerTurnAuthor",
    "Escalation",
    "EscalationAcknowledged",
    "EscalationAnswered",
    "EscalationClosed",
    "EscalationNotOpenError",
    "EscalationOpenError",
    "EscalationOpened",
    "EscalationReassigned",
    "EscalationState",
    "EscalationTaken",
    "EscalationWithdrawn",
    "IdempotencyConflictError",
    "InboxStatus",
    "LanguageMismatchError",
    "Turn",
    "TurnAudience",
    "TurnAuthorRole",
    "TurnCreated",
    "TurnKind",
    "ensure_speaks_case_language",
    "normalize_close_note",
    "normalize_escalation_text",
    "normalize_rating_comment",
    "normalize_rating_score",
    "normalize_turn_text",
    "preview_of",
    "search_key",
]
