"""Cases context: the case, its transcript, its assignment and the one-open-case rule."""

from cc_platform.domain.cases.assignment import Assignment
from cc_platform.domain.cases.case import (
    MAX_CLOSE_NOTE,
    Case,
    CaseClosure,
    normalize_close_note,
    preview_of,
    search_key,
)
from cc_platform.domain.cases.customer_case_slot import CustomerCaseSlot
from cc_platform.domain.cases.errors import CaseClosedError, IdempotencyConflictError
from cc_platform.domain.cases.events import (
    CASE_EVENTS,
    CaseAssigned,
    CaseClosed,
    CaseFirstResponded,
    CaseOpened,
    CaseQueued,
    CaseRead,
    CaseStatusChanged,
    TurnCreated,
)
from cc_platform.domain.cases.turn import MAX_TURN_TEXT, Turn, normalize_turn_text
from cc_platform.domain.cases.values import (
    CLOSABLE_STATUSES,
    OPEN_ASSIGNED_STATUSES,
    REPLYABLE_STATUSES,
    AssignmentReason,
    CaseChannel,
    CasePriority,
    CaseStatus,
    CloseReason,
    CustomerConversationStatus,
    CustomerTurnAuthor,
    InboxStatus,
    TurnAudience,
    TurnAuthorRole,
    TurnKind,
)

__all__ = [
    "CASE_EVENTS",
    "CLOSABLE_STATUSES",
    "MAX_CLOSE_NOTE",
    "MAX_TURN_TEXT",
    "OPEN_ASSIGNED_STATUSES",
    "REPLYABLE_STATUSES",
    "Assignment",
    "AssignmentReason",
    "Case",
    "CaseAssigned",
    "CaseChannel",
    "CaseClosed",
    "CaseClosedError",
    "CaseClosure",
    "CaseFirstResponded",
    "CaseOpened",
    "CasePriority",
    "CaseQueued",
    "CaseRead",
    "CaseStatus",
    "CaseStatusChanged",
    "CloseReason",
    "CustomerCaseSlot",
    "CustomerConversationStatus",
    "CustomerTurnAuthor",
    "IdempotencyConflictError",
    "InboxStatus",
    "Turn",
    "TurnAudience",
    "TurnAuthorRole",
    "TurnCreated",
    "TurnKind",
    "normalize_close_note",
    "normalize_turn_text",
    "preview_of",
    "search_key",
]
