#!/usr/bin/env node
/**
 * Generate `src/lib/api/schema.gen.ts` from the backend contract
 * (`../backend/openapi.json`) and format it with the project's prettier config.
 *
 *   pnpm gen:api          write the file
 *   pnpm gen:api --check  exit 1 if the committed file is stale (CI / slice gate)
 *
 * The backend side has the matching check:
 *   uv run python -m cc_platform.scripts.export_openapi --check
 */
import { readFile, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import openapiTS, { astToString } from 'openapi-typescript'
import * as prettier from 'prettier'

const root = new URL('..', import.meta.url)
const source = new URL('../backend/openapi.json', root)
const target = fileURLToPath(new URL('src/lib/api/schema.gen.ts', root))

const header = `/**
 * GENERATED by \`pnpm gen:api\` from backend/openapi.json. Do not edit by hand.
 * Import it only from \`src/lib/api/client.ts\` (the API boundary).
 */
`

const ast = await openapiTS(source)
const config = (await prettier.resolveConfig(target)) ?? {}
const output = await prettier.format(header + astToString(ast), { ...config, filepath: target })

if (process.argv.includes('--check')) {
  const current = await readFile(target, 'utf8').catch(() => '')
  if (current !== output) {
    console.error(
      'schema.gen.ts is stale: run `pnpm gen:api` (after exporting backend/openapi.json).',
    )
    process.exit(1)
  }
  console.warn('schema.gen.ts is up to date.')
} else {
  await writeFile(target, output)
  console.warn(`wrote ${target}`)
}
