"""People context: staff, their roles and teams, and how they sign in."""

from cc_platform.domain.people.admin_roster import ROSTER_ID, AdminRoster
from cc_platform.domain.people.availability import (
    AnalystAvailability,
    AvailabilityChangeReason,
    AvailabilityStatus,
)
from cc_platform.domain.people.errors import (
    AccountLockedError,
    EmailTakenError,
    LastAdminError,
    MfaChallengeInvalidError,
    PasswordRejectedError,
    StaffInvitedError,
    TeamInactiveError,
    TeamNameTakenError,
    TeamNotEmptyError,
)
from cc_platform.domain.people.events import (
    ONBOARDING_EVENTS,
    STAFF_ADMIN_EVENTS,
    TEAM_EVENTS,
    AccountLocked,
    LoginFailed,
    MfaChallengeIssued,
    MfaVerificationFailed,
    PasswordAccepted,
    SessionEnded,
    SessionStarted,
    StaffAccountUnlocked,
    StaffAvailabilityChanged,
    StaffCreated,
    StaffDeactivated,
    StaffInvitationAccepted,
    StaffInvitationCancelled,
    StaffInvitationResent,
    StaffInvitationSent,
    StaffLanguagesChanged,
    StaffMfaEnrolled,
    StaffPasswordReset,
    StaffPasswordResetLinkSent,
    StaffProfileUpdated,
    StaffReactivated,
    StaffRolesChanged,
    StaffTeamChanged,
    TeamCreated,
    TeamDeactivated,
    TeamReactivated,
    TeamRenamed,
)
from cc_platform.domain.people.invitation import INVITATION_TTL, Invitation, InvitationState
from cc_platform.domain.people.login_account import (
    TOTP_METHOD,
    AuthFactor,
    FailedAttemptCounter,
    FailedAttemptOutcome,
    LockoutPolicy,
    LoginAccount,
)
from cc_platform.domain.people.mfa import MfaChallenge, MfaChallengeStatus, MfaMethod, MfaPolicy
from cc_platform.domain.people.names import fold, normalize_person_name, normalize_team_name
from cc_platform.domain.people.password_policy import PasswordRule, password_violations
from cc_platform.domain.people.password_reset import (
    PASSWORD_RESET_TTL,
    PasswordReset,
    PasswordResetState,
)
from cc_platform.domain.people.session import SessionEndReason, StaffSession
from cc_platform.domain.people.staff import (
    ROLE_PRECEDENCE,
    AccountSetup,
    Language,
    Staff,
    StaffEdit,
    StaffRole,
    canonical_roles,
    normalize_email,
    sorted_languages,
)
from cc_platform.domain.people.team import Team

__all__ = [
    "INVITATION_TTL",
    "ONBOARDING_EVENTS",
    "PASSWORD_RESET_TTL",
    "ROLE_PRECEDENCE",
    "ROSTER_ID",
    "STAFF_ADMIN_EVENTS",
    "TEAM_EVENTS",
    "TOTP_METHOD",
    "AccountLocked",
    "AccountLockedError",
    "AccountSetup",
    "AdminRoster",
    "AnalystAvailability",
    "AuthFactor",
    "AvailabilityChangeReason",
    "AvailabilityStatus",
    "EmailTakenError",
    "FailedAttemptCounter",
    "FailedAttemptOutcome",
    "Invitation",
    "InvitationState",
    "Language",
    "LastAdminError",
    "LockoutPolicy",
    "LoginAccount",
    "LoginFailed",
    "MfaChallenge",
    "MfaChallengeInvalidError",
    "MfaChallengeIssued",
    "MfaChallengeStatus",
    "MfaMethod",
    "MfaPolicy",
    "MfaVerificationFailed",
    "PasswordAccepted",
    "PasswordRejectedError",
    "PasswordReset",
    "PasswordResetState",
    "PasswordRule",
    "SessionEndReason",
    "SessionEnded",
    "SessionStarted",
    "Staff",
    "StaffAccountUnlocked",
    "StaffAvailabilityChanged",
    "StaffCreated",
    "StaffDeactivated",
    "StaffEdit",
    "StaffInvitationAccepted",
    "StaffInvitationCancelled",
    "StaffInvitationResent",
    "StaffInvitationSent",
    "StaffInvitedError",
    "StaffLanguagesChanged",
    "StaffMfaEnrolled",
    "StaffPasswordReset",
    "StaffPasswordResetLinkSent",
    "StaffProfileUpdated",
    "StaffReactivated",
    "StaffRole",
    "StaffRolesChanged",
    "StaffSession",
    "StaffTeamChanged",
    "Team",
    "TeamCreated",
    "TeamDeactivated",
    "TeamInactiveError",
    "TeamNameTakenError",
    "TeamNotEmptyError",
    "TeamReactivated",
    "TeamRenamed",
    "canonical_roles",
    "fold",
    "normalize_email",
    "normalize_person_name",
    "normalize_team_name",
    "password_violations",
    "sorted_languages",
]
