"""The platform's event catalog: every event type it emits, with its payload, rendered from the
domain event classes into ``docs/platform/api/engine-signals.md`` (between two markers).

Usage: ``uv run python -m cc_platform.scripts.event_catalog [--doc PATH] [--check]``.
``--check`` exits with status 1 when the document is out of date (a test runs it too), so an
event type, a payload key or a ``schema_version`` can never change without the document.
"""

from __future__ import annotations

import argparse
import dataclasses
import importlib
import pkgutil
import sys
import types
import typing
from collections.abc import Iterator
from datetime import datetime
from pathlib import Path

import cc_platform
from cc_platform.bootstrap.settings import BACKEND_DIR
from cc_platform.domain.shared.events import (
    EVENT_CATALOG_VERSION,
    SCHEMA_VERSION_KEY,
    DomainEvent,
)

DEFAULT_DOC = BACKEND_DIR.parent / "docs" / "platform" / "api" / "engine-signals.md"
BEGIN = "<!-- event-catalog:begin (generated by cc_platform.scripts.event_catalog) -->"
END = "<!-- event-catalog:end -->"

_ENVELOPE = frozenset({"occurred_at", "actor", "entity_id", "case_id"})


def event_classes() -> list[type[DomainEvent]]:
    """Every concrete event class of the platform, one per type, sorted by type."""
    for module in pkgutil.walk_packages(cc_platform.__path__, prefix="cc_platform."):
        if ".scripts." not in module.name:
            importlib.import_module(module.name)
    found: dict[str, type[DomainEvent]] = {}
    pending: list[type[DomainEvent]] = [DomainEvent]
    while pending:
        for sub in pending.pop().__subclasses__():
            pending.append(sub)
            if sub.__module__.startswith("cc_platform.domain."):
                found[sub.event_type] = sub
    return [found[name] for name in sorted(found)]


@dataclasses.dataclass(frozen=True, slots=True)
class PayloadKey:
    key: str
    type: str
    nullable: bool
    omitted_when_null: bool
    free_text: bool


def payload_keys(event: type[DomainEvent]) -> list[PayloadKey]:
    """The payload as the event log stores it (without ``schema_version``)."""
    hints = typing.get_type_hints(event)
    keys: list[PayloadKey] = []
    for field in dataclasses.fields(event):
        if field.name in _ENVELOPE:
            continue
        kind, nullable = _describe(hints[field.name])
        key = event.payload_keys.get(field.name, field.name)
        keys.append(
            PayloadKey(
                key=key,
                type=kind,
                nullable=nullable,
                omitted_when_null=field.name in event.omitted_when_null,
                free_text=key in event.free_text_keys,
            )
        )
    return keys


def _describe(hint: object) -> tuple[str, bool]:
    args = typing.get_args(hint)
    if isinstance(hint, types.UnionType) or typing.get_origin(hint) is typing.Union:
        rest = [a for a in args if a is not type(None)]
        kind, _ = _describe(rest[0]) if len(rest) == 1 else (" | ".join(map(str, rest)), False)
        return kind, type(None) in args
    origin = typing.get_origin(hint)
    if origin in (tuple, list, frozenset, set):
        inner, _ = _describe(args[0])
        return f"{inner}[]", False
    if origin is dict or hint is dict:
        return "object", False
    named = {str: "string", int: "integer", bool: "boolean", float: "number"}
    if hint in named:
        return named[hint], False
    if hint is datetime:
        return "date-time", False
    if isinstance(hint, typing.TypeAliasType):  # JsonObject
        return "object", False
    raise TypeError(f"no catalog type for {hint!r}")


def _key_cell(key: PayloadKey) -> str:
    kind = key.type
    if key.nullable:
        kind += " (omitted when null)" if key.omitted_when_null else " or null"
    flag = " **free text**" if key.free_text else ""
    return f"`{key.key}`: {kind}{flag}"


def _families(classes: list[type[DomainEvent]]) -> Iterator[tuple[str, list[type[DomainEvent]]]]:
    families: dict[str, list[type[DomainEvent]]] = {}
    for event in classes:
        families.setdefault(event.event_type.split(".", 1)[0], []).append(event)
    yield from sorted(families.items())


def render(classes: list[type[DomainEvent]] | None = None) -> str:
    classes = classes if classes is not None else event_classes()
    lines = [
        BEGIN,
        "",
        f"Catalog version **{EVENT_CATALOG_VERSION}**: {len(classes)} event types. Every payload "
        f"also carries `{SCHEMA_VERSION_KEY}` (integer, the version in the `v` column). Types: "
        "`string` (an id, an enum value or a code unless marked **free text**), `integer`, "
        "`boolean`, `date-time` (ISO-8601 UTC, `Z`), `string[]`, `object`. "
        "**free text** marks a key that carries someone's words or a person's name: a consumer "
        "that must not read text drops it.",
        "",
    ]
    for family, events in _families(classes):
        lines += [f"#### `{family}.*`", "", "| Event | Entity | v | Payload |", "|---|---|---|---|"]
        for event in events:
            keys = payload_keys(event)
            cell = "<br>".join(_key_cell(k) for k in keys) if keys else "(no keys)"
            lines.append(
                f"| `{event.event_type}` | `{event.entity}` | {event.schema_version} | {cell} |"
            )
        lines.append("")
    lines.append(END)
    return "\n".join(lines) + "\n"


def splice(document: str, section: str) -> str:
    """``document`` with the generated section replaced (it must have both markers)."""
    start, end = document.find(BEGIN), document.find(END)
    if start < 0 or end < start:
        raise ValueError("the document has no event-catalog markers")
    return document[:start] + section + document[end + len(END) + 1 :]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--doc", type=Path, default=DEFAULT_DOC)
    parser.add_argument("--check", action="store_true", help="fail if the document is stale")
    args = parser.parse_args(argv)

    doc: Path = args.doc
    current = doc.read_text(encoding="utf-8")
    content = splice(current, render())
    if args.check:
        if current != content:
            print(f"{doc} is out of date; run cc_platform.scripts.event_catalog", file=sys.stderr)
            return 1
        return 0
    doc.write_text(content, encoding="utf-8")
    print(f"wrote {doc}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
